### ISSUE TITLE
Add padding and alignment for the homepage

### ISSUE THREAD

**Issue by Crystal-RainSlide** [NOtherDev/whatwebcando#56]
Minimum:
```css
.features-list-container .btn > i {
  margin-right: .5ch;
  margin-inline-end: .5ch;
}

.features-list-container .btn > span.support-info-placeholder {
  float: right;
}
```

Flexbox:

```
.features-list-container .btn {
  display: flex;
  flex-flow: row nowrap;
}
.features-list-container .btn > i {
  padding-right: .5ch;
  padding-inline-end: .5ch;
}
.features-list-container .btn > .support-info-placeholder {
  flex-grow: 1;
  text-align: end;
}
```

Before:
![图片](https://user-images.githubusercontent.com/16851802/65368737-9b864e00-dc77-11e9-95a0-d4eccbafcc5f.png)

After:
![图片](https://user-images.githubusercontent.com/16851802/65368768-e4d69d80-dc77-11e9-9402-138bb7f947d2.png)
